# sonar-project.properties
sonar.projectKey=ngohainnam_kash
sonar.organization=ngohainnam
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**,.next/**,prisma/migrations/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=kash
sonar.sourceEncoding=UTF-8
